<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Pipeline.CustomMiddleware</RootNamespace>
    <AssemblyName>04.Pipeline.CustomMiddleware</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\00.Common\Common.csproj" />
  </ItemGroup>

</Project>
