@host = http://localhost:5001

### Привітання
GET {{host}}/

### Середовище (сервіс із DI)
GET {{host}}/env

### Товари з каталогу (ICatalog з DI)
GET {{host}}/products

### Ініціювати graceful shutdown
GET {{host}}/shutdown
