@host = http://localhost:5009

### Constraint :int
GET {{host}}/products/1

### Несумісний сегмент → 404 (маршрут не підійшов)
GET {{host}}/products/abc

### Літеральний сегмент виграє в параметра
GET {{host}}/products/featured

### Кілька параметрів + :guid
GET {{host}}/products/1/reviews/3fa85f64-5717-4562-b3fc-2c963f66afa6

### :alpha
GET {{host}}/categories/laptops

### Значення за замовчуванням
GET {{host}}/pages

### Catch-all {**path}
GET {{host}}/files/img/2026/logo.png

### Генерація URL через LinkGenerator
GET {{host}}/link/7
