@host = http://localhost:5002

### Головна
GET {{host}}/

### OpenAPI-документ
GET {{host}}/openapi/v1.json

### Scalar UI (відкрийте у браузері)
GET {{host}}/scalar

### Поточне середовище
GET {{host}}/env

### Який сервер і на яких адресах слухає
GET {{host}}/server

### Значення з конфігурації (різне для Dev / Prod)
GET {{host}}/config

### Лише в Development
GET {{host}}/dev/ping
