<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Rest.Versioning</RootNamespace>
    <AssemblyName>17.Rest.Versioning</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <!-- Версіонування для контролерів MVC (додає .AddMvc(), атрибути [ApiVersion]). -->
    <PackageReference Include="Asp.Versioning.Mvc" Version="10.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\00.Common\Common.csproj" />
  </ItemGroup>

</Project>
