<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Rest.Versioning</RootNamespace>
    <AssemblyName>17.Rest.Versioning</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\00.Common\Common.csproj" />
  </ItemGroup>

</Project>
